name: API Keep-Alive

on:
  schedule:
    # Keep-alive ping - every 10 minutes to prevent hibernation
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep API Alive
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
          echo "Pinging API to keep it alive..."
          # Try multiple endpoints to ensure the API stays warm
          curl -f -s -o /dev/null "$API_URL/" || echo "Root endpoint failed"
          curl -f -s -o /dev/null "$API_URL/docs" || echo "Docs endpoint failed"
          curl -f -s -o /dev/null "$API_URL/health" || echo "Health endpoint failed"
          echo "Keep-alive ping completed"

  health-check:
    runs-on: ubuntu-latest
    # Run health check for manual triggers
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: API Health Check
        env:
          API_URL: ${{ secrets.API_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Performing comprehensive health check..."
          
          # Check basic connectivity
          echo "Checking API connectivity..."
          curl -f -s -w "Status: %{http_code}, Time: %{time_total}s\n" "$API_URL/" || echo "Root endpoint failed"
          
          # Check docs endpoint
          echo "Checking documentation..."
          curl -f -s -w "Status: %{http_code}, Time: %{time_total}s\n" "$API_URL/docs" || echo "Docs endpoint failed"
          
          # Check articles endpoint (if exists)
          echo "Checking articles endpoint..."
          curl -f -s -w "Status: %{http_code}, Time: %{time_total}s\n" \
            -H "X-API-Key: $API_KEY" \
            "$API_URL/api/articles?limit=1" || echo "Articles endpoint failed"
          
          echo "Health check completed" 
